# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: apple.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'apple.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61pple.proto\"s\n\x08\x41ppleReq\x12\r\n\x05\x62ssid\x18\x01 \x01(\t\x12$\n\x08location\x18\x02 \x01(\x0b\x32\x12.AppleReq.Location\x1a\x32\n\x08Location\x12\x0b\n\x03lat\x18\x01 \x01(\x03\x12\x0b\n\x03lon\x18\x02 \x01(\x03\x12\x0c\n\x04unk1\x18\x03 \x01(\x03\"_\n\tAppleResp\x12\x0c\n\x04unk1\x18\x01 \x01(\x03\x12\x17\n\x04wifi\x18\x02 \x03(\x0b\x32\t.AppleReq\x12\x0c\n\x04unk2\x18\x03 \x01(\x05\x12\x0c\n\x04unk3\x18\x04 \x01(\x05\x12\x0f\n\x07\x41PIName\x18\x05 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'apple_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_APPLEREQ']._serialized_start=15
  _globals['_APPLEREQ']._serialized_end=130
  _globals['_APPLEREQ_LOCATION']._serialized_start=80
  _globals['_APPLEREQ_LOCATION']._serialized_end=130
  _globals['_APPLERESP']._serialized_start=132
  _globals['_APPLERESP']._serialized_end=227
# @@protoc_insertion_point(module_scope)
